export const ML: Record<string, string> = {
  delts: "Shoulders (delts)", rearDelts: "Rear delts", chest: "Chest", triceps: "Triceps",
  biceps: "Biceps", forearms: "Forearms / grip", traps: "Traps & upper back", lats: "Lats (back width)",
  lowerback: "Lower back", abs: "Abs", obliques: "Obliques", glutes: "Glutes",
  quads: "Quads (thighs)", hamstrings: "Hamstrings", calves: "Calves",
};

export interface Exercise {
  name: string;
  equip: string;
  pattern: string;
  muscles: string[];
  feel: string;
  steps: string[];
  mistakes: string[];
  unit?: string;
}

export const EX: Record<string, Exercise> = {
  dbBench: {
    name: "Dumbbell Bench Press", equip: "Dumbbells + bench", pattern: "hpush",
    muscles: ["chest", "delts", "triceps"],
    feel: "Across your chest, a little in front shoulders and back of arms. Never in the front of the shoulder joint sharply.",
    steps: ["Lie on bench, feet flat on floor, dumbbells over chest, palms forward.", "Lower slowly (2–3 sec) until elbows are slightly below the bench, ~45° from your body.", "Press up and slightly inward until arms are straight. Don't bang the dumbbells together."],
    mistakes: ["Flaring elbows straight out at 90° — strains shoulders.", "Bouncing the weight off the chest. Control the way down."],
  },
  ohpSeated: {
    name: "Seated Dumbbell Shoulder Press", equip: "Dumbbells + upright bench", pattern: "vpush",
    muscles: ["delts", "triceps"],
    feel: "On top and sides of your shoulders, triceps near lockout. Not in your lower back.",
    steps: ["Sit with back fully against the pad, dumbbells at shoulder height, palms forward.", "Press straight up until arms are nearly locked, weights finishing over your head — not in front.", "Lower with control back to ear level. Don't drop below that while your shoulders are weak."],
    mistakes: ["Arching the lower back off the pad to push more weight.", "Pressing the weights forward instead of straight overhead."],
  },
  inclinePush: {
    name: "Incline Pushup", equip: "Bench / smith bar", pattern: "hpush",
    muscles: ["chest", "delts", "triceps", "abs"],
    feel: "Chest and back of arms working, abs tight like a plank.",
    steps: ["Hands on a bench, slightly wider than shoulders. Body in one straight line, toes back.", "Lower your chest to the bench over 2–3 seconds, elbows ~45° from your sides.", "Push back up to straight arms. Squeeze glutes the whole time so hips don't sag."],
    mistakes: ["Hips sagging or sticking up — body must stay a straight plank.", "Half reps — chest should touch (or nearly touch) the bench."],
  },
  latRaise: {
    name: "Dumbbell Lateral Raise", equip: "Light dumbbells", pattern: "raise",
    muscles: ["delts"],
    feel: "On the side caps of your shoulders. If your traps/neck burn, the weight is too heavy.",
    steps: ["Stand tall, dumbbells at your sides, slight bend in elbows.", "Raise arms out to the sides to shoulder height — like pouring water from jugs, pinkies slightly up.", "Lower slowly over 2–3 sec. The way down builds the muscle."],
    mistakes: ["Swinging the body to throw the weights up.", "Going above shoulder height — unnecessary and risky for you now."],
  },
  facePull: {
    name: "Cable Face Pull", equip: "Cable + rope, face height", pattern: "hpull",
    muscles: ["rearDelts", "traps"],
    feel: "Behind your shoulders and between the shoulder blades. This is your posture-fixer.",
    steps: ["Set cable at face height, grab rope with thumbs pointing back toward you.", "Pull the rope toward your eyes, elbows high and wide, until hands are beside your ears.", "Squeeze shoulder blades together 1 sec, return slowly."],
    mistakes: ["Pulling to the chest instead of the face — turns it into a row.", "Using heavy weight and leaning back. Keep it light and strict."],
  },
  plank: {
    name: "Plank", equip: "Bodyweight", pattern: "plank",
    muscles: ["abs", "obliques"],
    feel: "Deep in your abs, like bracing for a punch. Never in the lower back.",
    steps: ["Forearms on floor, elbows under shoulders, legs straight behind you.", "Squeeze glutes, tuck hips slightly, push the floor away through forearms.", "Breathe normally. Stop the set when your hips start to sag."],
    mistakes: ["Hips too high (no work) or sagging (back pain).", "Holding your breath."],
  },
  sidePlank: {
    name: "Side Plank", equip: "Bodyweight", pattern: "plank",
    muscles: ["obliques", "abs"],
    feel: "Down the side of your waist facing the floor.",
    steps: ["Lie on your side, elbow under shoulder, feet stacked (or staggered to start).", "Lift hips so your body forms a straight diagonal line.", "Hold, breathing. Repeat both sides."],
    mistakes: ["Hips dipping toward the floor.", "Shoulder of the supporting arm collapsing — push the floor away."],
  },
  latPulldown: {
    name: "Lat Pulldown", equip: "Cable machine, wide bar", pattern: "vpull",
    muscles: ["lats", "biceps", "rearDelts"],
    feel: "In the sides of your back under the armpits. If only arms burn, you're pulling with biceps.",
    steps: ["Grip slightly wider than shoulders, sit with thighs locked under pads, chest tall.", "Pull the bar to your upper chest by driving elbows down into your back pockets.", "Pause 1 sec, then let the bar rise slowly until arms are fully stretched."],
    mistakes: ["Leaning way back and yanking with body weight.", "Pulling behind the neck — never do this."],
  },
  cableRow: {
    name: "Seated Cable Row", equip: "Cable row machine", pattern: "hpull",
    muscles: ["lats", "traps", "biceps"],
    feel: "Between your shoulder blades and mid-back. This directly fights your desk/bike hunch.",
    steps: ["Sit tall, knees soft, grab the handle with arms stretched, chest up.", "Pull the handle to your belly button, squeezing shoulder blades together.", "Return slowly until arms straight, letting shoulders stretch forward slightly."],
    mistakes: ["Rocking back and forth with the lower back.", "Shrugging shoulders up toward ears while pulling."],
  },
  deadHang: {
    name: "Dead Hang", equip: "Pull-up bar", pattern: "hang",
    muscles: ["lats", "forearms", "traps"],
    feel: "Stretch through lats and serious work in your grip/forearms.",
    steps: ["Grab the bar slightly wider than shoulders, palms away.", "Hang with straight arms, feet off floor, shoulders pulled slightly down away from ears.", "Hold as long as grip allows. This builds your pull-up foundation."],
    mistakes: ["Fully relaxing the shoulders into the ears — keep slight tension.", "Swinging."],
  },
  pullupNeg: {
    name: "Pull-up Negative", equip: "Pull-up bar + box", pattern: "vpull",
    muscles: ["lats", "biceps", "forearms"],
    feel: "Lats and biceps fighting hard on the way down. This is THE pull-up builder.",
    steps: ["Use a box to jump so your chin is above the bar.", "Lower yourself as slowly as you can — aim 4–5 full seconds — until arms are straight.", "Step back on the box and repeat. Quality over quantity."],
    mistakes: ["Dropping fast in the bottom half — fight the whole way.", "Doing too many; 4–5 slow ones beat 10 fast ones."],
  },
  dbCurl: {
    name: "Dumbbell Bicep Curl", equip: "Dumbbells", pattern: "curl",
    muscles: ["biceps", "forearms"],
    feel: "Front of the upper arm. Elbows pinned to your sides.",
    steps: ["Stand tall, dumbbells at sides, palms forward.", "Curl up without moving the elbows forward; squeeze at the top.", "Lower over 2–3 seconds fully straight."],
    mistakes: ["Swinging hips to lift heavy weight.", "Half reps that never fully straighten the arm."],
  },
  bandPullApart: {
    name: "Band Pull-apart", equip: "Resistance band", pattern: "raise",
    muscles: ["rearDelts", "traps"],
    feel: "Behind your shoulders and between shoulder blades.",
    steps: ["Hold a band at shoulder height, arms straight, hands shoulder-width.", "Pull the band apart until it touches your chest, squeezing shoulder blades.", "Return slowly. Great as warmup and posture medicine."],
    mistakes: ["Bending elbows — keep arms straight.", "Shrugging up while pulling."],
  },
  deadBug: {
    name: "Dead Bug", equip: "Bodyweight, lying", pattern: "core",
    muscles: ["abs"],
    feel: "Deep abs working to keep your lower back glued to the floor.",
    steps: ["Lie on your back, arms straight up, knees bent 90° over hips.", "Slowly lower your RIGHT arm overhead and LEFT leg toward floor at the same time.", "Keep lower back pressed flat. Return, switch sides."],
    mistakes: ["Lower back arching off the floor — shorten the range if it does.", "Rushing. Slow = effective."],
  },
  gobletSquat: {
    name: "Goblet Squat", equip: "One dumbbell, held at chest", pattern: "squat",
    muscles: ["quads", "glutes", "abs"],
    feel: "Thighs and glutes. Heels stay glued to the floor.",
    steps: ["Hold a dumbbell vertically against your chest, feet shoulder-width, toes slightly out.", "Sit down between your heels until thighs are at least parallel, chest tall.", "Drive through your whole foot to stand. Knees track over toes."],
    mistakes: ["Heels lifting / knees caving inward.", "Leaning the chest far forward — the dumbbell keeps you honest."],
  },
  rdl: {
    name: "Romanian Deadlift", equip: "Barbell (start 20kg empty bar)", pattern: "hinge",
    muscles: ["hamstrings", "glutes", "lowerback"],
    feel: "A deep stretch in the back of your thighs. NEVER pain in the spine — if so, stop and reset flat back.",
    steps: ["Hold the bar at hip level, feet hip-width, slight knee bend.", "Push your hips BACK (like closing a car door with your butt) letting the bar slide down your thighs.", "Stop when hamstrings stretch hard (~mid-shin), back flat, then drive hips forward to stand."],
    mistakes: ["Rounding the lower back — this is the #1 thing to avoid with your back history.", "Bending knees too much, turning it into a squat."],
  },
  legPress: {
    name: "Leg Press", equip: "Leg press machine", pattern: "squat",
    muscles: ["quads", "glutes", "hamstrings"],
    feel: "Thighs and glutes, safely supported — good while your back recovers.",
    steps: ["Feet shoulder-width, middle of the platform. Back and hips stay glued to the pad.", "Lower the platform until knees reach ~90°, no deeper if your hips start curling up.", "Press through whole foot without locking knees hard at the top."],
    mistakes: ["Going so deep your lower back rolls off the pad.", "Locking the knees violently at the top."],
  },
  calfRaise: {
    name: "Calf Raise", equip: "Machine or step + dumbbell", pattern: "calf",
    muscles: ["calves"],
    feel: "Burn in the back of the lower legs.",
    steps: ["Balls of feet on the edge of a step, heels hanging.", "Lower heels for a full 2-sec stretch at the bottom.", "Rise as high as possible on your toes, squeeze 1 sec."],
    mistakes: ["Bouncing fast with tiny range.", "Skipping the bottom stretch — that's half the exercise."],
  },
  inclineWalk: {
    name: "Incline Walk (finisher)", equip: "Treadmill 5–6% incline", pattern: "cardio",
    muscles: ["quads", "calves", "glutes"], unit: "min",
    feel: "Heart rate up, breathing harder but able to speak short sentences.",
    steps: ["Set incline 5–6%, speed ~6 km/h.", "Walk tall, don't hang on the handles — that deletes the work.", "Pump your arms naturally."],
    mistakes: ["Holding the rails (cuts calorie burn ~30%).", "Zero incline strolling — it must feel like a hill."],
  },
  shrugs: {
    name: "Dumbbell Shrugs", equip: "Dumbbells", pattern: "raise",
    muscles: ["traps"],
    feel: "Top of your shoulders / base of neck.",
    steps: ["Stand tall, heavy-ish dumbbells at your sides.", "Shrug shoulders straight UP toward your ears.", "Squeeze 1 sec, lower slowly. No rolling."],
    mistakes: ["Rolling shoulders in circles — straight up and down only.", "Using the arms to lift."],
  },
  hangKneeRaise: {
    name: "Hanging Knee Raise", equip: "Pull-up bar", pattern: "hang",
    muscles: ["abs", "forearms"],
    feel: "Lower abs, plus grip. Doubles as pull-up grip training.",
    steps: ["Hang from the bar with straight arms.", "Pull knees up toward your chest, slightly curling the hips.", "Lower slowly without swinging."],
    mistakes: ["Swinging momentum.", "Only lifting thighs to 90° — curl the hips for abs to work."],
  },
  treadmillInt: {
    name: "Treadmill Intervals", equip: "Treadmill", pattern: "cardio",
    muscles: ["quads", "hamstrings", "calves"], unit: "min",
    feel: "Hard breathing in work minutes, recovering in walk minutes. This drives VO₂max.",
    steps: ["Warm up walking 5 min.", "Weeks 1–3: brisk incline walk 30–35 min. Weeks 4+: 1 min jog / 2 min walk × 8–10.", "Weeks 7+: 1 min fast / 1.5 min easy × 8. Cool down 3 min."],
    mistakes: ["Sprinting too fast too early — build gradually at 93kg to protect knees.", "Skipping the warm-up minutes."],
  },
  pushupMax: {
    name: "Pushups (max sets)", equip: "Bodyweight", pattern: "hpush",
    muscles: ["chest", "delts", "triceps", "abs"],
    feel: "Chest and arms. Track your max — watch it climb from 6 to 15+.",
    steps: ["Hands slightly wider than shoulders, body one straight line.", "Chest to the floor, elbows ~45°.", "Push up. Stop 1 rep before total failure."],
    mistakes: ["Hips sagging.", "Neck poking forward — look at the floor slightly ahead."],
  },
  tablePush: {
    name: "Incline Pushup (table/bed)", equip: "Sturdy table or bed", pattern: "hpush",
    muscles: ["chest", "delts", "triceps", "abs"],
    feel: "Chest and arms, abs braced.",
    steps: ["Hands on the table edge, slightly wider than shoulders, walk feet back to a straight-body angle.", "Lower chest to the edge over 2–3 sec, elbows ~45°.", "Push back up. When 15 is easy, use something lower — sofa, then floor."],
    mistakes: ["Hips sagging.", "Standing too upright so it's too easy — walk the feet back."],
  },
  pikePush: {
    name: "Pike Pushup", equip: "Bodyweight (chair later)", pattern: "vpush",
    muscles: ["delts", "triceps"],
    feel: "Top of your shoulders — this is your home shoulder press.",
    steps: ["From pushup position, walk feet in and lift hips high — body like an upside-down V.", "Bend elbows to lower the TOP of your head toward the floor between your hands.", "Press back up. Harder version: feet on a chair."],
    mistakes: ["Turning it into a normal pushup by dropping hips — hips stay high.", "Landing on your face — lower with control."],
  },
  floorPushup: {
    name: "Floor Pushup", equip: "Bodyweight", pattern: "hpush",
    muscles: ["chest", "delts", "triceps", "abs"],
    feel: "Chest, arms, braced abs.",
    steps: ["Hands slightly wider than shoulders, body straight from head to heels.", "Chest to floor, 2–3 sec down, elbows ~45° from sides.", "Press up fully. Knees-down version is fine to finish a set."],
    mistakes: ["Hips sagging or piking up.", "Cutting depth as you tire — drop to knees instead."],
  },
  bpLatRaise: {
    name: "Backpack Lateral Raise", equip: "Backpack with books (~4–6kg)", pattern: "raise",
    muscles: ["delts"],
    feel: "Side caps of the shoulders.",
    steps: ["Hold backpack handle in one hand at your side.", "Raise the arm out to shoulder height, slight elbow bend.", "Lower over 3 sec. Switch arms."],
    mistakes: ["Swinging the bag with momentum.", "Raising above shoulder height."],
  },
  tableRow: {
    name: "Table Row", equip: "Sturdy table", pattern: "hpull",
    muscles: ["lats", "traps", "biceps"],
    feel: "Between shoulder blades and the sides of your back — your home lat pulldown.",
    steps: ["Lie under a sturdy table, grab the edge, body straight, heels on floor.", "Pull your chest to the edge, squeezing shoulder blades.", "Lower over 2–3 sec to straight arms. Bend knees to make it easier, straighten to make it harder."],
    mistakes: ["Hips sagging — keep the plank.", "Half reps; chest should reach the edge."],
  },
  bpRow: {
    name: "Backpack Bent-over Row", equip: "Loaded backpack (8–12kg)", pattern: "hpull",
    muscles: ["lats", "traps", "biceps"],
    feel: "Side of your back and mid-back; flat spine like the RDL position.",
    steps: ["Hinge forward with flat back, one hand on a chair for support.", "Row the backpack to your ribs, elbow brushing your side.", "Lower slowly. Full stretch at the bottom."],
    mistakes: ["Rounding the back — same rule as deadlifts.", "Yanking with the arm only; lead with the elbow."],
  },
  towelRow: {
    name: "Towel Door Row", equip: "Towel + solid door", pattern: "hpull",
    muscles: ["lats", "biceps", "forearms"],
    feel: "Back and biceps, plus grip work.",
    steps: ["Loop a towel around the handles of a SOLID closed door (hinge side safer). Test it first.", "Lean back with straight arms, body straight, heels planted.", "Pull your chest to your hands, squeeze 1 sec, lower over 3–4 sec."],
    mistakes: ["Using a flimsy door or handle — test before loading.", "Bending at the hips; the body stays a straight plank."],
  },
  bpCurl: {
    name: "Backpack Curl", equip: "Loaded backpack", pattern: "curl",
    muscles: ["biceps", "forearms"],
    feel: "Front of upper arm.",
    steps: ["Hold the top handle with one or both hands, elbows pinned to sides.", "Curl up, squeeze, lower over 3 sec.", "Add books to progress."],
    mistakes: ["Swinging the load.", "Elbows drifting forward."],
  },
  superman: {
    name: "Superman Hold", equip: "Floor", pattern: "core",
    muscles: ["lowerback", "glutes"],
    feel: "Lower back and glutes working — directly strengthens your achy area.",
    steps: ["Lie face down, arms extended in front.", "Lift chest, arms and legs a few cm off the floor at the same time.", "Hold 15–20 sec breathing, lower, repeat."],
    mistakes: ["Cranking the neck up to look forward — keep neck neutral.", "Holding breath."],
  },
  bwSquat: {
    name: "Bodyweight Squat", equip: "Bodyweight (backpack later)", pattern: "squat",
    muscles: ["quads", "glutes"],
    feel: "Thighs and glutes; heels glued down.",
    steps: ["Feet shoulder-width, toes slightly out, arms forward for balance.", "Sit between your heels to at least parallel, chest tall.", "Stand by pushing the floor away. Add a loaded backpack hugged at the chest when 20 reps is easy."],
    mistakes: ["Knees caving in.", "Shallow quarter-reps."],
  },
  revLunge: {
    name: "Reverse Lunge", equip: "Bodyweight", pattern: "lunge",
    muscles: ["quads", "glutes"],
    feel: "Front-leg thigh and glute. Easier on knees than forward lunges.",
    steps: ["Stand tall, step one foot BACK into a long stride.", "Lower until the back knee hovers just above the floor, front shin vertical.", "Push through the front heel to return. Alternate legs."],
    mistakes: ["Short stride making the front knee shoot past the toes.", "Leaning the torso far forward."],
  },
  slRdl: {
    name: "Single-leg RDL", equip: "Backpack in one hand", pattern: "hinge",
    muscles: ["hamstrings", "glutes", "lowerback"],
    feel: "Hamstring of the standing leg + balance. Great back medicine done strictly.",
    steps: ["Stand on one leg, soft knee, backpack in the opposite hand.", "Hinge at the hip, letting the free leg float back, back flat, until you feel the hamstring stretch.", "Squeeze the glute to stand. Hold a wall for balance at first."],
    mistakes: ["Rounding the back to reach lower.", "Twisting the hips open — keep them square to the floor."],
  },
  gluteBridge: {
    name: "Glute Bridge", equip: "Floor", pattern: "bridge",
    muscles: ["glutes", "hamstrings"],
    feel: "Squeeze in the glutes at the top, NOT in the lower back.",
    steps: ["Lie on your back, knees bent, feet flat near your hips.", "Drive through heels to lift hips until body is straight from knees to shoulders.", "Squeeze glutes hard 2 sec at the top, lower slowly."],
    mistakes: ["Overextending so the lower back arches — stop at straight.", "Pushing through toes instead of heels."],
  },
  stairCalf: {
    name: "Stair Calf Raise", equip: "Step / stair", pattern: "calf",
    muscles: ["calves"],
    feel: "Burn in the back of the lower leg with a deep stretch at the bottom.",
    steps: ["Balls of feet on the stair edge, heels hanging, hand on rail for balance.", "Lower heels for a 2-sec stretch.", "Rise to tip-toes, squeeze 1 sec. Single-leg when easy."],
    mistakes: ["Bouncing.", "Tiny range of motion."],
  },
  ytw: {
    name: "Prone Y-T-W Raise", equip: "Floor, face down", pattern: "core",
    muscles: ["rearDelts", "traps"],
    feel: "Behind your shoulders and between shoulder blades — the home face pull.",
    steps: ["Lie face down, forehead near the floor.", "Raise straight arms into a Y shape, hold 2 sec, lower. Then T shape. Then W (elbows bent, squeeze blades).", "That's 1 rep of each; do 8 rounds. Thumbs point UP throughout."],
    mistakes: ["Lifting the chest/arching hard — only the arms lift.", "Rushing; 2-sec holds do the work."],
  },
  wallHandstand: {
    name: "Wall Handstand Hold (week 4+)", equip: "Wall", pattern: "vpush",
    muscles: ["delts", "triceps", "abs"],
    feel: "Shoulders fully loaded — advanced shoulder builder.",
    steps: ["From hands and knees, feet against the wall, walk feet UP the wall while walking hands closer.", "Stop at a diagonal you can hold steady — no need to go fully vertical.", "Hold 15–20 sec, breathe, walk back down with control."],
    mistakes: ["Going too vertical too soon.", "Collapsing down instead of walking down."],
  },
  legRaise: {
    name: "Lying Leg Raise", equip: "Floor", pattern: "core",
    muscles: ["abs"],
    feel: "Lower abs; lower back stays pressed into the floor.",
    steps: ["Lie flat, hands under hips, legs straight up.", "Lower legs slowly toward the floor only as far as your back stays flat.", "Raise back up. Bend knees to make it easier."],
    mistakes: ["Back arching off the floor — shorten the range.", "Dropping the legs fast."],
  },
  walkOutdoor: {
    name: "Brisk Walk / Stairs", equip: "Outdoors or staircase", pattern: "cardio",
    muscles: ["quads", "calves", "glutes"], unit: "min",
    feel: "Breathing hard enough that long sentences are difficult.",
    steps: ["Walk briskly 30–40 min, or climb stairs continuously 15–20 min.", "Pump your arms, tall posture.", "Weeks 4+: add 1-min fast bursts every 5 min."],
    mistakes: ["Strolling pace — it must feel like training.", "Skipping it on home days; this is your VO₂max engine."],
  },
  circuit: {
    name: "Bodyweight Circuit", equip: "Bodyweight", pattern: "cardio",
    muscles: ["quads", "chest", "abs"], unit: "rounds",
    feel: "Full-body, heart pounding — conditioning + endurance.",
    steps: ["10 squats → 8 pushups → 20 jumping jacks → 30-sec plank.", "Rest max 60 sec, repeat 3 rounds.", "Add a round every 2 weeks."],
    mistakes: ["Form falling apart when tired — slow down instead.", "Resting 3+ minutes; keep it tight."],
  },
  bpOhp: {
    name: "Backpack Overhead Press", equip: "Loaded backpack", pattern: "vpush",
    muscles: ["delts", "triceps"],
    feel: "Top of the shoulders.",
    steps: ["Hold the backpack by its side handles at chest height.", "Press it straight overhead to locked arms.", "Lower with control to chin level. Add books to progress."],
    mistakes: ["Arching the lower back — squeeze glutes and ribs down.", "Pressing forward instead of straight up."],
  },
};
